### ISSUE TITLE
Question on things which patch their own resources

### ISSUE THREAD

**Issue by aaron-trout** [pusher/faros#134]
So I am attempting to deploy Istio (1.1.2) using Faros. Istio's sidecar injector webhook looks like this:

```yaml
---
# Source: istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: istio
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
```

...however when the sidecar injector service container starts, it tries to patch that object:

```
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:11.220992Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:11.616587Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:12.019073Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:12.418993Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:12.820355Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:13.293608Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
istio-sidecar-injector-549585c8d9-8n6nt sidecar-injector-webhook 2019-04-15T16:49:13.625550Z    info    Detected a change in CABundle, patching MutatingWebhookConfiguration again
```

Of course, Faros also notices that the resource changed, and changes it back:

```
faros-controller-manager-0 manager 2019/04/15 16:48:46 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
faros-controller-manager-0 manager 2019/04/15 16:48:47 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
faros-controller-manager-0 manager 2019/04/15 16:48:47 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
faros-controller-manager-0 manager 2019/04/15 16:48:47 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
faros-controller-manager-0 manager 2019/04/15 16:48:48 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
faros-controller-manager-0 manager 2019/04/15 16:48:48 Updated child MutatingWebhookConfiguration /istio-sidecar-injector
```

This is pretty hilarious but also quite annoying :P

Any ideas on how to handle this? It is a pretty convenient yet strange behaviour from Istio I guess... Presumably Istio supports some kind of way to provide your own CAs rather than having it generate one... but more generally... is there any way that Faros could know about this change and allow it?
