### ISSUE TITLE
Support reading GitHub OAuth Token from Kube Secrets

### ISSUE THREAD

**Issue by tshak** [pusher/faros#85]
## Scenario
Some prefer using GitHub OAuth tokens instead of SSH to access private repositories on GitHub. This is already supported by setting the `repository` in `GitTrack` to: https://<your-token-here>:x-oauth-basic@github.com. The problem with this approach is that the token is stored in plain text. 

## Proposal
Add support for HTTP basic auth. Since most git servers (e.g. GitHub, Bitbucket) support authenticating via basic HTTP auth for OAuth, this allows for both username/password and OAuth token authentication. 

 To support this  we can add a `type` to the `GitTrackDeployKey` that accepts `HTTPBasicAuth` and `SSH` and defaults to `SSH`. When set to `HTTPBasicAuth` we will authenticate using basic HTTP authentication. In this case, we expect that the secret is formatted as `username:password` (similar to `curl -u ...`). 

### Example GitTrack Spec
This example utilizes the new `HTTPBasicAuth` support.
```yaml
spec:
  reference: master
  repository: https://github.com/my/repo
  deployKey:
    key: myKey
    secretName: mySecret
    type: HTTPBasicAuth
```

**Comment by tshak** [comment]
Feedback welcome. I'm going to work on a PR for the proposed approach in the mean time.

**Comment by JoelSpeed** [comment]
Hey @tshak, thanks for raising this issue and I agree, we should definitely be adding support for this!

>Add a `credType` to the `GitTrackDeployKey` that accepts `OAuthToken` and `SSH` and defaults to `SSH`. When set to `OAuthToken` we will authenticate using the following:

Two points on this, I don't think we need to call `credType` `credType`, `type` would be sufficient. (I would like to ultimately rename `GitTrackDeployKey` to `GitTrackDeploySecret`).

Secondly, given this is basically the work needed to enable `basic` auth, why not create a `basic` `credType` and then have a username field? Would this be preferred? This would likely be a change to the existing spec and would need us to bump from `v1alpha1` so I guess a TODO for this might be better for now

> This only works for git servers that support a token using the `x-oauth-token` as the username and `<token>` as the secret.

Let's make sure we document this one then

**Comment by tshak** [comment]
Thanks for the feedback. I'm out of town for a couple of weeks so I'm going to be slower to respond. 

> Two points on this, I don't think we need to call `credType` `credType`, `type` would be sufficient. (I would like to ultimately rename `GitTrackDeployKey` to `GitTrackDeploySecret`).

I went back and forth on this. I'm happy just calling it `type`  especially considering a rename in the future to `GitTrackDeploySecret`. Keep in mind that in go we'll still have to call it `credType` since `type` is a reserved keyword.

> Secondly, given this is basically the work needed to enable `basic` auth, why not create a `basic` `credType` and then have a username field?

The fact that we're using basic auth is an implementation detail. In fact I'd prefer that we use an HTTP header instead of basic auth but that would require changes to `git-store` and I wanted to keep the scope of this change small. 

I considered just enabling basic auth. We would then have to specify two keys to read from the secret though. One for the `username` and one for the `password`. This breaks `GitTrackDeployKey` and we would probably want to create a totally different configuration section. This is all doable but it's more work. On the other hand, supporting this may make it easier for people to support other non standard authentication styles (e.g. token only in username vs. hard coded token username and token in password). 

I could go either way on this. I'll try to get a 3rd point of view on my end.

**Comment by tshak** [comment]
I've updated the readme with an alternative proposal that we should consider.

**Comment by tshak** [comment]
@JoelSpeed  Any thoughts on the Alternative that I added to the readme of this issue?

**Comment by wimdec** [comment]
Another proposal for the secret passing could be the following:
```
spec:
  reference: master
  repository: https://github.com/my/repo 
  deployKey:
    type: SSH | Basic (default: SSH)
    # SecretName is the name of the secret containing the private key or username:password pair.
    name: mySecret 
    # Key is the Secret's key containing the private key or username:password pair.
    key:  keyinsecret 
```
In case of Basic, the secret should be created with username:password pair:
kubectl create secret generic mySecret --from-literal=keyinsecret=x-oauth-token:123456789abcdef

This has advantage that the change is backwards compatible and supports any username/password.
