### ISSUE TITLE
Support deleting resources

### ISSUE THREAD

**Issue by sebastianroesch** [pusher/faros#92]
Currently, Faros supports creating and updating resources. Deleting resources requires manual work, for example by deleting the resource in Kubernetes as well as in the GitOps repository.

**Consideration:**
One possibility would be to compare the resources in the GitOps repository to the resources in the cluster managed by Faros and delete the ones that no longer exist in the GitOps repository. This could result in resources accidentally being deleted, be it by developers, a misconfiguration of Faros or other reasons.
A safer way would be to be more intentional about the resources that should be deleted, by marking them for deletion in the GitOps repository. 

**Proposal:**
Add an annotation to mark a resource to be deleted by Faros. 
Setting the `faros.pusher.com/resource-state` annotation to `marked-for-deletion` will remove the resource in the Kubernetes cluster on the next `Reconcile()`.
The annotation is optional and defaults to `active`, which would tell Faros to create or update the resource as it normally does.

Example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
  labels:
    app: nginx
  annotations:
    faros.pusher.com/resource-state: "marked-for-deletion"
```
